language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL=26
  - ANDROID_BUILD_TOOLS_VERSION=26.0.2
  - secure: du8NTQ15i5t42wbEunvhIy0917abbcWKiZmMcbS2SKo1cGVs8MjFr9k4or/uc00qRuRlYEnCZeg32gFWRNe22VUpjrD2Fb9EblBqfYOtTohXeuL4Tp5vviAlB4Joa7VvQUQ6EZmMn3jzzdbHHqglJpRaasY+9pwpCGQNVUsFt/tG4/5T0WP2U23jEmYDLoqWY83wkcW8HP+xrO9RmzvyD/d+soMRAMHPhb2KqkiszC3Ev7xfGMY25F+E4r6ZbYKOVKJVju1pBqKoR8Mj5DLqqTdRUU7FlixiuAc0qimeCVlNNS0BZEFD375QHWd95L9pJMKtUxaTG9iKZPHvMq4D4Uo2pphnwtndoS/PY/pvnivARu9St2UKmcbbVqjVecmIipsfwj3Vq2ZaF0OXtcvtDwOtAU98fbKt1EhWQDEQd+AIDzy79Mf72+b6xZ39OuCAAxT43OXv7M475lE0KRvZnQO26t7N3WrOyxZFUZDUSIdMiyX73f+9qIZ4sQYtzo7lu9XWi+dQ0A3z1aIPNo9uJnJ09SmoahDx7fDw1deLBE1mliJpEY1gewgPlssa4W8ZQyd16KMnAB1xkHoHCGiJ4VGANrCJVGdUAwDshWcIbyJfbvGbHaL/pwhmq3ne7afiVYM7Hf3l7cmchOodwsYW62nfJ84ozIX2A2tdI5C7UVY=
  - secure: dZ8af0UyHSTXEl11GrwKEDCLSpgP4V8XDqyoPcwaleTC9qUVQ2CoIOqeqF2Bv0uAOei/vJLnoPwtjV7MkirlbjZDIj9k3UnVVfZ3X3mnHmUL0lcZ1XdwSYCMFhlPEqUZUUe5J9+hjpQetlP4hWooRR1+nXzBhQLiOLbZds/TEVpXp5J3QAS0MFTLZ2m0ZLcw8oOKku/yQ8ax1Fz/+/XYoR/QFIPmS3Noinr596Ny4ECeN3rGW1g2fzLZw9erofB+puGAd9gzL6xNMGT3pmn+P1qSgRdeR8LSFYe1jbKDuGoK1gpbE7/hcGYCsYcnsIbjX0iN3xSj5MnOy69yLhNKLDHSeGwxWTr82PgrD0dnHzTnYIygEbKcLWaynfjhazQnN63R4FNRmSG0tWQcT4lz+Rng4B9n4fZ9LwS9z1axI4YeP4tiHjUH4LLYT9L0T5lTSbpAgbNvshj0PrpbdXerUxE83wLgQnoIBb19LJq39BaI15jfe3LdSYYQRHe5JgRAHmQujfq/RAyJJpzeOC2XKtTv3FuiguB10vnERf1etitUXUpD2PKYNxZrxApRwH2v/WzrNLsqgRUQbeJEUVzuSWB5I6IWSkIT46iwimhcUB6NRiHowRV9p4wRe+j0YK52Fl5J4jiZVa8wYsri0I1fgN4ZlKuBahD9K0kUunxZrXo=
android:
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-26
before_script:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
#script:
#- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
#- "./gradlew build check"

#before_install:
#- openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in keystore.jks.enc -out keystore.jks -d

script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"

before_deploy:
- openssl aes-256-cbc -K $encrypted_657e27e4d3ee_key -iv $encrypted_657e27e4d3ee_iv -in keystore.jks.enc -out keystore.jks -d
- cd app/build/outputs/apk/release
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${TRAVIS_BUILD_DIR}/keystore.jks -storepass $storepass -keypass $keypass app-release-unsigned.apk hoangth12495
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/zipalign -v 4 app-release-unsigned.apk TravisAndroid.apk"
- cd -
- scripts/tag.sh

deploy:
  provider: releases
  on:
    branch: master
  file: "app/build/outputs/apk/release/TravisAndroid.apk"
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: "wg17uIWC2+5lTv1534Kvp5xO9sabPuxZQKiA7MqqYeAM6m/Dw1T9Fc8POoZJPFnHKtFdqHJsJb/LVtcbg3iIsrMVPrLsVcWFSUgYIxni9ZHzGtmt1aOxDZ6bKOrXMLstLkdUbNMQl6Ed4P70pXGVbTCeV0eaunzkA+Dc7f4Dk9imA1gKNbaGM6bGTUPrEpTX2a3LQSUkL1/wLSL3vlght7knEnyBT4vci4us9Z2t3rgzQtLKwtwb1B5MojIR9tzLdfu4EBuxGVnkBKTq6E5okhgmHMSvYFifANyo5HmMC4y2O3lFgr9odTktiakIFljgdlkInnDti0PlZbk00vH0EFboUJEJvX9KAQfgvmZYMZDjtPUXgtDeh4cTrk9eU/Q00nv+vwW1NQrIag4SfJB+lYy5cjqTEeiZ5u5FXTjMCZ7eG1Yo676PmAOx4vPPoUWg6lYPmWxek9Sv3XynB/KWP1CDYpmnSPhmErd+rxy42GPTD08BmD341qM+p9T6j/zEummoD68Le0Da6nIAIDXbZi1OmJTuM2etlkjaIllJGeNHRWICGkpJUh+v5R/CjG2s3kXxa17SCfunHPzZ7XfNcoFWJ7omEIhl3TwiHgQ+60d18Tzs/b1dCRhbt0hgHdMq3YR9U5mBdsHHo3zmQ0jUANm/+wODP401QWE0CJkGcbM="

