language: android

script: "./gradlew build"
android:
  components:
    - platform-tools
    - tools
    - build-tools-26.1.1
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-15
    - sys-img-armeabi-v7a-android-21